update

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -38,8 +38,11 @@ jobs:
         run: |
           CONDA_ENV=openxla_preCI_${{ github.event.pull_request.number }}_${{ runner.name }}
           source ${HOME}/miniconda3/bin/activate ${CONDA_ENV}
-          wget https://github.com/bazelbuild/bazel/releases/download/5.3.0/bazel-5.3.0-installer-linux-x86_64.sh
-          bash bazel-5.3.0-installer-linux-x86_64.sh --user
+          which bazel
+          if [ $? -eq 1 ]; then
+            wget https://github.com/bazelbuild/bazel/releases/download/5.3.0/bazel-5.3.0-installer-linux-x86_64.sh
+            bash bazel-5.3.0-installer-linux-x86_64.sh --user
+          fi
           export PATH=$PATH:/home/sdp/bin
           source /home/sdp/.bazel/bin/bazel-complete.bash
           bazel --version
@@ -65,26 +68,26 @@ jobs:
               echo "Build Failed"
               exit 1
           fi
-      - name: UT testing
-        run: |
-          CONDA_ENV=openxla_preCI_${{ github.event.pull_request.number }}_${{ runner.name }}
-          source ${HOME}/miniconda3/bin/activate ${CONDA_ENV}
-          basekit_path=/home/sdp
-          source ${basekit_path}/intel/oneapi/compiler/latest/env/vars.sh
-          source ${basekit_path}/intel/oneapi/mkl/latest/env/vars.sh
-          folder_path="/home/sdp/xuming/ut"
-          pip install absl-py
-          # Loop through all Python files in the folder and execute them
-          for file in "$folder_path"/*.py; do
-                  echo $file
-                  if [ -f "$file" ]; then
-                  echo "Running $file..."
-                  python "$file"
-                  if [ ${PIPESTATUS[0]} -eq 0 ]; then
-                    echo "run $test_case successfully"
-                  else
-                      echo "run $test_case failed"
-                  fi
-                  echo "----------------------------------------"
-              fi
-          done
+#      - name: UT testing
+#        run: |
+#          CONDA_ENV=openxla_preCI_${{ github.event.pull_request.number }}_${{ runner.name }}
+#          source ${HOME}/miniconda3/bin/activate ${CONDA_ENV}
+#          basekit_path=/home/sdp
+#          source ${basekit_path}/intel/oneapi/compiler/latest/env/vars.sh
+#          source ${basekit_path}/intel/oneapi/mkl/latest/env/vars.sh
+#          folder_path="/home/sdp/xuming/ut"
+#          pip install absl-py
+#          # Loop through all Python files in the folder and execute them
+#          for file in "$folder_path"/*.py; do
+#                  echo $file
+#                  if [ -f "$file" ]; then
+#                  echo "Running $file..."
+#                  python "$file"
+#                  if [ ${PIPESTATUS[0]} -eq 0 ]; then
+#                    echo "run $test_case successfully"
+#                  else
+#                      echo "run $test_case failed"
+#                  fi
+#                  echo "----------------------------------------"
+#              fi
+#          done
