add parallel run ut

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -69,26 +69,42 @@ jobs:
               echo "Build Failed"
               exit 1
           fi
-#      - name: UT testing
-#        run: |
-#          CONDA_ENV=openxla_preCI_${{ github.event.pull_request.number }}_${{ runner.name }}
-#          source ${HOME}/miniconda3/bin/activate ${CONDA_ENV}
-#          basekit_path=/home/sdp
-#          source ${basekit_path}/intel/oneapi/compiler/latest/env/vars.sh
-#          source ${basekit_path}/intel/oneapi/mkl/latest/env/vars.sh
-#          folder_path="/home/sdp/xuming/ut"
-#          pip install absl-py
-#          # Loop through all Python files in the folder and execute them
-#          for file in "$folder_path"/*.py; do
-#                  echo $file
-#                  if [ -f "$file" ]; then
-#                  echo "Running $file..."
-#                  python "$file"
-#                  if [ ${PIPESTATUS[0]} -eq 0 ]; then
-#                    echo "run $test_case successfully"
-#                  else
-#                      echo "run $test_case failed"
-#                  fi
-#                  echo "----------------------------------------"
-#              fi
-#          done
+     - name: UT testing
+       run: |
+        CONDA_ENV=openxla_preCI_${{ github.event.pull_request.number }}_${{ runner.name }}
+        source ${HOME}/miniconda3/bin/activate ${CONDA_ENV}
+        basekit_path=/home/sdp
+        source ${basekit_path}/intel/oneapi/compiler/latest/env/vars.sh
+        source ${basekit_path}/intel/oneapi/mkl/latest/env/vars.sh
+        folder_path="/home/sdp/xuming/ut"
+        pip install absl-py
+        # Loop through all Python files in the folder and execute them
+        dev_num=4 #IDC have 4 1100 pvc card
+        # Create a pipe and bind the file descriptor 6
+        tmp_fifofile="/tmp/$$.fifo"
+        mkfifo $tmp_fifofile
+        exec 6<>$tmp_fifofile
+        rm $tmp_fifofile
+        # Writing NUM_PROC blank data to the pipe
+        for ((i = 0; i < $dev_num; i++)); do
+            echo "$i"
+        done >&6
+
+        for file in "$folder_path"/*.py; do
+          # read one data from the pipe
+          read -u6 id
+          {
+            echo "running ut on device-$id"
+            key=$(basename $file .py)
+            echo $file
+            ZE_AFFINITY_MASK="$id" python $file
+            if [ ${PIPESTATUS[0]} -eq 0 ]; then
+              echo "run $file successfully"
+            else
+                echo "run $test_case failed"
+            fi
+            # writing one data to the pipe for the next task
+            echo $id >&6
+          } &
+        done
+
