Update intel_openxla_ci.yml

diff --git a/.github/workflows/intel_openxla_ci.yml b/.github/workflows/intel_openxla_ci.yml
--- a/.github/workflows/intel_openxla_ci.yml
+++ b/.github/workflows/intel_openxla_ci.yml
@@ -17,58 +17,58 @@ jobs:
       - name: Check out repository code
         uses: actions/checkout@v3
 
-      - name: Prepare Conda Environment
-        run: |
-          set +e
-          CONDA_ENV=openxla_preCI_${{ github.event.pull_request.number }}_${{ runner.name }}
-          source /opt/miniconda/bin/activate ${CONDA_ENV}
-          if [ $? -ne 0 ]; then
-              echo 'conda env does not exist'
-              conda create -n ${CONDA_ENV} python=3.10 -y
-              conda activate ${CONDA_ENV}
-          fi
-          pip install jax==0.4.20 jaxlib==0.4.20
-          pip install numpy
-          conda install libstdcxx-ng==12.2.0 -c conda-forge
-          pip install absl-py
-          pip list | grep numpy
-          pip list | grep jax
+      # - name: Prepare Conda Environment
+      #   run: |
+      #     set +e
+      #     CONDA_ENV=openxla_preCI_${{ github.event.pull_request.number }}_${{ runner.name }}
+      #     source /opt/miniconda/bin/activate ${CONDA_ENV}
+      #     if [ $? -ne 0 ]; then
+      #         echo 'conda env does not exist'
+      #         conda create -n ${CONDA_ENV} python=3.10 -y
+      #         conda activate ${CONDA_ENV}
+      #     fi
+      #     pip install jax==0.4.20 jaxlib==0.4.20
+      #     pip install numpy
+      #     conda install libstdcxx-ng==12.2.0 -c conda-forge
+      #     pip install absl-py
+      #     pip list | grep numpy
+      #     pip list | grep jax
 
-      - name: Build openXLA
-        run: |
-          set +e
-          CONDA_ENV=openxla_preCI_${{ github.event.pull_request.number }}_${{ runner.name }}
-          source /opt/miniconda/bin/activate ${CONDA_ENV}
-          which bazel
-          if [ $? -eq 1 ]; then
-            wget https://github.com/bazelbuild/bazel/releases/download/5.3.0/bazel-5.3.0-installer-linux-x86_64.sh
-            bash bazel-5.3.0-installer-linux-x86_64.sh --user
-          fi
-          export PATH=$PATH:/home/sdp/bin
-          source /home/sdp/.bazel/bin/bazel-complete.bash
-          bazel --version
-          pip list | grep numpy
-          pip install numpy
-          basekit_path=/home/sdp
-          complier_path=${basekit_path}/intel/oneapi/compiler/latest
-          mkl_path=${basekit_path}/intel/oneapi/mkl/latest
-          cp /home/sdp/openXLA_demoxla_auto_configure_mkl.exp .
-          ls
-          python --version
-          chmod +x ./openXLA_demoxla_auto_configure_mkl.exp
-          ./openXLA_demoxla_auto_configure_mkl.exp $complier_path $mkl_path
-          bazel clean --expunge --async
-          bazel build //xla/tools/pip_package:build_pip_package
-          ./bazel-bin/xla/tools/pip_package/build_pip_package ./
-          build_result=${PIPESTATUS[0]}
-          echo $build_result
-          if [ "$build_result" = "0" ];then
-              echo "Build successful"
-              pip install *.whl
-          else
-              echo "Build Failed"
-              exit 1
-          fi
+      # - name: Build openXLA
+      #   run: |
+      #     set +e
+      #     CONDA_ENV=openxla_preCI_${{ github.event.pull_request.number }}_${{ runner.name }}
+      #     source /opt/miniconda/bin/activate ${CONDA_ENV}
+      #     which bazel
+      #     if [ $? -eq 1 ]; then
+      #       wget https://github.com/bazelbuild/bazel/releases/download/5.3.0/bazel-5.3.0-installer-linux-x86_64.sh
+      #       bash bazel-5.3.0-installer-linux-x86_64.sh --user
+      #     fi
+      #     export PATH=$PATH:/home/sdp/bin
+      #     source /home/sdp/.bazel/bin/bazel-complete.bash
+      #     bazel --version
+      #     pip list | grep numpy
+      #     pip install numpy
+      #     basekit_path=/home/sdp
+      #     complier_path=${basekit_path}/intel/oneapi/compiler/latest
+      #     mkl_path=${basekit_path}/intel/oneapi/mkl/latest
+      #     cp /home/sdp/openXLA_demoxla_auto_configure_mkl.exp .
+      #     ls
+      #     python --version
+      #     chmod +x ./openXLA_demoxla_auto_configure_mkl.exp
+      #     ./openXLA_demoxla_auto_configure_mkl.exp $complier_path $mkl_path
+      #     bazel clean --expunge --async
+      #     bazel build //xla/tools/pip_package:build_pip_package
+      #     ./bazel-bin/xla/tools/pip_package/build_pip_package ./
+      #     build_result=${PIPESTATUS[0]}
+      #     echo $build_result
+      #     if [ "$build_result" = "0" ];then
+      #         echo "Build successful"
+      #         pip install *.whl
+      #     else
+      #         echo "Build Failed"
+      #         exit 1
+      #     fi
 
       - name: UT testing
         run: |
@@ -85,7 +85,7 @@ jobs:
           cd jax_test/openxla/
           mkdir -p ./logs/ut
           pip install -r /home/sdp/xuming/test-requirements.txt
-          find ./tests -name "*.py" | sed 's#\./##g' > ut_list.txt
+          find ./tests -name "*.py" | sed 's#\./##g' |& tee ut_list.txt
           file_path=./ut_list.txt
           reference_file=./distribute_ut_list.txt
           
