change to GPU build

diff --git a/.github/workflows/Public_Jax_CI.yml b/.github/workflows/Public_Jax_CI.yml
--- a/.github/workflows/Public_Jax_CI.yml
+++ b/.github/workflows/Public_Jax_CI.yml
@@ -27,15 +27,15 @@ jobs:
             conda create -n ${CONDA_ENV} python=3.10 -y
             conda activate ${CONDA_ENV}
         fi
-        # conda install -c conda-forge gcc=12.1.0
-        # conda install gcc_linux-64
-        # conda install gxx_linux-64
         sudo apt install g++ python python3-dev -y | true
         pip uninstall jax jaxlib -y
         pip install numpy wheel build  
         #This CI is for public jax 
-        git clone https://github.com/google/jax.git && cd jax && git checkout ${{ inputs.gha_runner }}
-        pip install -r ./build/test-requirements.txt
+        #git clone https://github.com/google/jax.git && cd jax && git checkout ${{ inputs.gha_runner }}
+        git clone -b yang/runtime https://github.com/Intel-tensorflow/xla  
+        git clone -b path-to-jax https://github.com/google/jax.git && cd jax && git checkout ceb198582b62b9e6f6bdf20ab74839b0cf1db16e
+        git apply ../test/jax.patch  
+        pip install -r jax/build/test-requirements.txt
     - name: Build Jax
       run: |
         set +e
@@ -43,16 +43,17 @@ jobs:
         source /opt/miniconda/bin/activate ${CONDA_ENV}
         #build jax 
         cd jax
-        python build/build.py   #CPU
+        #python build/build.py   #CPU
+        python build/build.py --enable_sycl --bazel_options=--override_repository=xla=../xla
         build_result=${PIPESTATUS[0]}
         echo $build_result
         if [ "$build_result" = "0" ];then
-            echo "Build successful"
-            pip install dist/*.whl --force-reinstall
-            pip install -e .   #install jax
+          echo "Build successful"
+          #pip install tests/*.whl   #cpu
+          pip install -e . && pip install dist/jaxlib_xxx.whl        
         else
-            echo "Build Failed"
-            exit 1
+          echo "Build Failed"
+          exit 1
         fi
     - name: UT testing
       run: |
@@ -65,7 +66,6 @@ jobs:
         mkdir -p ./logs/ut
         echo "$commit_hash" |& tee ./logs/ut/$commit_hash.txt
         find ./tests -name "*.py" | sed 's#\./##g' |& tee ut_list.txt
-
         # Check if the file exists
         file_path=./ut_list.txt
         if [ -f "$file_path" ]; then
@@ -84,7 +84,6 @@ jobs:
             echo "File not found: $file_path"
             exit
         fi
-
     - name: Upload CI Data
       uses: actions/upload-artifact@v3
       with:
